import type { MemecoinMindsetLesson } from "./memecoinMindsetLessons";

export const ALPHA_PLAYBOOK_LESSONS: MemecoinMindsetLesson[] = [
  {
    num: "01",
    title: "Full memecoin trading course",
    tips: [
      "Memecoins are an attention market — edge comes from speed, narrative selection, and emotional control, not classic TA",
      "Setup: PC with multiple monitors running Axiom, Twitter, Discord, and Phantom simultaneously — milliseconds matter",
      "Axiom Pulse filters: set specific launch protocols (Pump.fun, Bonk, Bags) and minimum market cap (~11k) to cut illiquid trash",
      "Wallet tracking is for reverse-engineering winners, not blind copy-trading — watch what they buy, when, and how consistent their P&L is",
      "The Alpha Filter: (1) Market condition check — is volume flowing? (2) Narrative valuation — will people see it, react, and for how long? (3) Inefficiency check — has CT caught on yet or are you early?",
      "Memecoins run on narratives, not RSI or MACD — a good narrative ties into current metas, has a large audience, and has catalysts that sustain attention",
      "Solo trading is a death sentence — serious traders operate in groups that divide scanning, wallet watching, and social tracking",
      "Allocation ranges: 1–2% per speculative snipe, 5–7% for rotations, 10–15% for top-conviction meta plays",
      "Four types of tilt to watch for: revenge, desperation, validation, and hope tilt — each one destroys differently",
      "Crypto is a gamified extraction system — value transfers from uninformed to those with edge. Know your level",
    ],
  },
  {
    num: "02",
    title: "The $1.3M month strategy",
    tips: [
      "Trade attention, not charts — memecoins are belief systems with liquidity, driven by culture and narrative",
      "Curate a crypto-only Twitter feed: follow real traders and narrative snipers, avoid faceless shill accounts that dump on followers",
      "Axiom Pulse: 95–99% of it is trash — hot market = hunt New Pairs with 11k+ market cap filter; slow market = stick to Migrated only",
      "On-chain due diligence: check deployer history (thousands of tokens = avoid), bundle wallets, insider holdings, snipers, and linked Twitter accounts",
      "Split buys across multiple wallets to hide size and manage risk — 1% supply per wallet avoids looking like a target on-chain",
      "Case study — Yeezy coin ($1.1M profit): tracked insider wallets loading pre-launch, entered early, set mental targets based on Iggy's Mother coin (~250M cap), sold aggressively once Kanye publicly endorsed at ~3B market cap",
      "Case study — AI video coin ($500k profit): found at ~30k market cap with VC backing (Paradigm), weaker coins with no backing were already at millions — classic mispricing",
      "Real profit only counts when moved to stable assets or fiat — crypto money is fake money until cashed out",
      "Journaling reveals what actually prints: consistently lost buying coins trending on Twitter, consistently won buying based on early wallet flow before Twitter caught on",
    ],
  },
  {
    num: "03",
    title: "Two strategies for $7,582/day",
    tips: [
      "Strategy 1 — Ruthless high-velocity scalping: exploit short bursts of volume on trending narratives, sell into other people's confirmation, not yours",
      "Scalp rules: detach from narratives (you're here to get paid, not be right), many small 1–2 SOL wins beat chasing one hero trade",
      "Entry triggers: early ignition on big green 1-min volume, controlled 60–80% retrace after first spike, or flash dump sweep that gets instantly bought by respected wallets",
      "Exit rules: scale into euphoria (big green candles or catalyst news), kill on weakness (1-min volume dies = immediate exit), don't chase the top",
      "Axiom scalp settings: 60% slippage buy / 40% sell, 0.05 priority bribe, MEV on, quick buys 4–10 SOL, Pulse filters $5k+ volume and $11k+ market cap",
      "Strategy 2 — The Alpha Filter: three-stage system to find the 1% worth holding for 3x–100x+",
      "Stage 1 (Market): lots of runners = risk-on, weak markets = protect capital",
      "Stage 2 (Narrative): grade on reach, reaction triggers, ceiling, and shelf life",
      "Stage 3 (Inefficiency): CT hasn't caught on + lagging similar pumped coins + insiders loading = mispriced window",
      "Case study — Trump coin: $12.6M group profit, personally $4M — caught at $500M cap when the most influential man in the world launching a coin was severely undervalued for a multi-billion meta",
    ],
  },
  {
    num: "04",
    title: "The shortest guide you'll ever need",
    tips: [
      "Identity drives action: reframe yourself as \"I extract value from attention markets\" instead of \"I'm a gambler hoping to get lucky\"",
      "Three-part alpha filter: (1) market condition — are coins migrating and is there a strong narrative? (2) narrative evaluation — score reach, reaction, ceiling, shelf life (3) inefficiency — is CT late, are smart wallets loading?",
      "If a coin doesn't hit at least three of the four narrative criteria strongly, pass with no exceptions",
      "Three-wallet system: main wallet (up to 50 SOL) for high-conviction, test wallet (1–3 SOL) for new plays, vault cold wallet to sweep profits weekly",
      "Journal four things per trade: the narrative, why you entered, why you exited, what you'd change — five minutes that compound into your biggest edge",
      "Claims: 3k → 500k on video coin, 151x on Trump coin for $12M group profits, personally $1M on $Z — all framed as systematic narrative exploitation, not luck",
    ],
  },
  {
    num: "05",
    title: "$0 to $100K full course",
    tips: [
      "Liquidity is the tide — when global M2 expands and central banks are loose, memecoins explode; when they tighten (like 2022), memecoins get crushed hardest",
      "Check: is Bitcoin healthy (the ocean), is global M2 rising, where are we in the cycle — this decides when to be aggressive vs sit out",
    ],
  },
  {
    num: "06",
    title: "The boring $100K/month strategy",
    tips: [
      "Most people lose because they chase hype, think with the herd, and have no filter, sizing, or exit plan — the edge is being boring and systematic",
      "Three pillars: sector flow (only trade during early euphoria, not fatigue), narrative analysis (score story, storytellers, timing/catalyst), risk-reward matrix (only enter when upside clearly outweighs downside)",
    ],
  },
  {
    num: "07",
    title: "1-minute scalping system",
    tips: [
      "Scalping memecoins = exploiting short bursts of attention, not holding for long-term moves — seconds-to-minutes trades on coins with strong short-term narrative and real volume",
      "Uses Nova (Cosmo + Ignite) instead of Axiom for scalps — Ignite flags new deployments getting early wallet stacking, volume, and narrative classification",
      "Ignite shows when it first pinged a coin, initial market cap, and current multipliers (2x, 3x, 4x since ping) — front-run before CT catches on",
      "Three ingredients of a good scalp: (1) legit enough to trade (not obviously nuked or trapped in a bundle), (2) narrative that catches eyes even briefly, (3) real volume with wallets stacking on raw new launches",
      "Case study — Office coin: Ignite pinged early, entered at 21k cap, controlled ~6% supply, sold into spikes at ~80k, netted $3.3k — fake backstory didn't matter when early enough to beat the house",
      "Case study — Journey coin: made $6k profit but missed a potential 100x — consistent exits beat chasing every last multiple",
      "Risk: size 5–10% of trenching wallet per scalp, never all-in, cut immediately if 1-minute volume dies — accept small 10% losses rather than 50–90% death bags",
      "Target 2–3 strong scalps per day — sometimes the best trade is not trading at all",
    ],
  },
  {
    num: "08",
    title: "$1,000/day alpha filter deep dive",
    tips: [
      "Uses Nova with Cosmo (real-time new pairs) and Ignite (algorithmic coin alerts trained on months of runner data) — Ignite pings early tokens and surging coins with market cap at ping vs current cap",
      "Noise reduction: filter minimum 15k market cap and 8k volume, disable dynamic bonding curve filter to avoid crash coins that nuke 99%",
      "Narrative > pure scalping: scalping 50 coins a day is a losing game — slippage/fees kill you; narratives last longer and pay more",
      "Beginners should start with migrated/graduated coins that passed an initial survival test, not raw new launches",
      "Case study — Yeezy ($1.1M profit): celebrity meta environment, benchmarked against other celebrity coins, scaled out once it flipped Mother's ATH and after the key catalyst played out",
      "Case study — Tally (~$20k profit, avoided rug): entered at 67k cap, suspicious wallets suppressing price, trimmed and fully exited after founder's buy, avoided total loss when founder got hacked",
      "Execution settings: 25% slippage, default priority/tips, MEV on — track specific wallets for trend awareness but never pure copy-trade",
      "Focus Ignite on surging coins above ~50k market cap and do deeper due diligence from there",
    ],
  },
  {
    num: "09",
    title: "7 lessons from $20M in crypto",
    tips: [
      "1. Obsession over everything — 18-hour days of research, tracking Twitter, contracts, wallets, and narratives; everyone he knows who made life-changing money was simply obsessed",
      "2. Psychology determines results — trading is 90% mental; blew early accounts from overconfidence, fear, revenge trading, and FOMO, not bad strategy",
      "3. Risk management is the lifeline — most blow up from overtrading or oversizing; risk ≤2% per trade, never widen stops, only move them up",
      "4. Master capital rotation — big money comes from understanding how attention rotates between narratives (AI, political, culture, new chains), not marrying one theme",
      "5. Narrative identification — four questions: what audience, why would they buy, attention ceiling, when will attention die? Pre-define exits so they're unemotional",
      "6. You don't need to trade daily — one of his best months (~$1.3M) came from only 10 trading days; distinguish opportunity from mere movement",
      "7. Accountability and journaling — after 100+ logged trades you see when you overtrade, how emotions sabotage you, and which setups actually work",
    ],
  },
  {
    num: "10",
    title: "$500/day beginner framework",
    tips: [
      "~40,000 coins launch daily on-chain but fewer than 1% migrate and most trend to zero — nearly everyone is trading garbage without a filter",
      "Most traders lose because they chase pumps, FOMO after big runs, copy influencer calls, buy into 30–60% insider bundles, oversize, and emotionally manage drawdowns",
      "2025 is a serial deployer environment — assume every new coin has a bundle, wait for bundles to exit and the coin to prove strength, then enter",
      "Case study — Black Pill coin: massive cultural presence via TikTok/YouTube/Twitter edits, accumulated under $100k cap when culture attention was high but crypto natives hadn't caught on",
      "Case study — VVM (Vibe Virtual Machine): bought at 100–120k cap during hot Bags meta, anticipated catalysts (Anthropic engineer dev claiming fees, Bags founder backing with large buys), exited at ~1.3M for roughly 10x",
      "Tracking on-chain health: look at how many pairs are bonding and whether migrated coins hold — if conditions are cold, don't trade; inactive half of January 2025 yet still ~$114k by being highly selective",
      "You cannot chart-trade memecoins — if you don't understand the story, meme, cultural hook, and catalysts, you should not buy regardless of the chart",
      "Starting with $500: set up tools, curate Twitter, join a serious community, learn the alpha filter, be greedy with entries, size so one loss can't wipe you, journal every trade",
    ],
  },
  {
    num: "11",
    title: "The 7-year crypto playbook",
    tips: [
      "Core pillars: read market cycles, control emotions, practice strict risk management, use Bitcoin as the foundation, treat altcoins as tools to accumulate more BTC",
      "The 4-year Bitcoin cycle is evolving due to institutions (BlackRock, Fidelity, nation-states, ETFs) — above 50-week MA = bullish, below = bearish",
      "Markets don't take your money, your emotions do — FOMO, revenge trading, and tilt destroy accounts more than crashes",
      "Never risk more than 1–2% per trade; predefine stop loss and aim for at least 1:2 risk-to-reward before entering",
      "Example allocation: ~75% cold storage (BTC + some alts), ~20% active trading capital, tiny % for gambles — sweep excess profits from trading wallet into cold storage",
      "Bitcoin thesis: competing with gold (~$20T), not other crypto; even 10% gold share implies 10x+ — DCA regardless of noise, hardware wallets, never trade your core stack",
      "Altcoin rules: cap at ~25% of portfolio, pick 5–8 high-conviction alts, deeply research problem/team/edge/TAM/catalysts, sell when they stop outperforming BTC",
    ],
  },
  {
    num: "12",
    title: "69 seconds to millionaire mindset",
    tips: [
      "The top 0.1% are simply willing to do the hard, uncommon work that the 99.9% avoid — that's the entire answer",
      "Study your niche obsessively: started with Fortnite videos, researched the audience deeply, and figured it out — the approach applies to any space",
      "At the start a million things can go wrong but only a few actually do — quit complaining, eat the plan",
      "Take full accountability for every outcome; every problem is your responsibility to learn from",
    ],
  },
  {
    num: "13",
    title: "2026 beginner's free course",
    tips: [
      "Memecoins aren't dead — more launches than ever, better tools, same retail attention; the edge is having the best filter to cut through rugs, fake narratives, and noise",
      "Twitter is your heartbeat monitor: For You page must be pure crypto — follow real traders, narrative snipers, builders, and KOLs so you see narratives as they form",
      "Three wallets: trench wallet (50–100 SOL max) for new-pair hunting, main wallet for higher-conviction migrated plays, vault wallet (cold storage) for long-term wealth — sweep profits regularly",
      "Crypto money is fake until it's in stablecoin or cold storage — core profit-taking rule",
      "Alpha Filter Stage 1 — Market condition: use Axiom Pulse to see on-chain volume (>$20M daily), migration rates, and whether new launches get real buys; decide risk-on vs risk-off",
      "Alpha Filter Stage 2 — Narrative evaluation: will people see it, how will they react, what's the attention ceiling (use comparable coins), how long can attention last? If you can't answer all four quickly, don't buy",
      "Alpha Filter Stage 3 — Inefficiency: search the ticker in Axiom's Twitter tracker — if lots of big accounts are already tweeting, you're probably late; look for coins lagging peers with similar/better backing",
    ],
  },
];
