import type { MemecoinMindsetLesson } from "./memecoinMindsetLessons";

export const FORTUNE_PLAYBOOK_LESSONS: MemecoinMindsetLesson[] = [
  {
    num: "01",
    title: "$2K → $200K on a single trade",
    tips: [
      "Five-step framework: find the right coin, read price action, size risk, execute entries, have a strict exit plan",
      "Used Dexscreener to spot video coins on Base during AI/tech meta — checked Twitter followers, dev identity, and backers (Paradigm, Magic Eden, Blur)",
      "Low liquidity + strong backers at 150k cap = early, not dead — thesis was the team would add liquidity later as the major catalyst",
      "Bought in multiple tranches averaging ~30k market cap — never full-size your position in one click due to volatility",
      "Took initial investment out on first breakout volume, then scaled out aggressively as it hit multi-million cap",
      "When the dev tweeted it wasn't the official coin, he was mostly out already because his exit plan prioritized principal protection",
    ],
  },
  {
    num: "02",
    title: "Full 2026 trading course",
    tips: [
      "Setup: PC with multiple monitors, Twitter for narratives, Phantom wallet, Axiom as primary trading bot with 30% slippage, 0.03 priority/bribe, MEV protection on",
      "Axiom filters: Pump.fun only, minimum 15k market cap, quick-buy sized to your portfolio",
      "Narrative evaluation: what's the story, why is it valuable, is it part of a movement or pure speculation, what future bull catalysts exist?",
      "Alpha plays (narrative leaders with highest cap) vs beta plays (derivatives that can reach ~10% of the alpha's cap but die harder in pullbacks)",
      "Legitimacy checks: top-10 holder %, dev holding, snipers, insider wallets, bundle percentage, and orange Twitter logo (recycled account = almost always a scam)",
      "Community = cult strength: look for active Twitter, engaged Telegram/Discord, communities that survived multiple drawdowns",
      "Two types of capitulation: price-based (drawdown too painful) and time-based (impatience during sideways action) — both prevented by proper sizing",
      "Average in AND out: buy 50% initially, add on dips; sell 10–25% at each profit threshold or catalyst event",
      "Journal four questions per trade: narrative, why you bought, why you held, why you sold",
    ],
  },
  {
    num: "03",
    title: "$800/day Twitter strategy",
    tips: [
      "Twitter-driven system: use Axiom's Twitter tracker with a curated list of top narrative accounts to catch coins before they pop",
      "When a tweet spawns a coin: assess the bull catalyst, check Dexscreener for older OG versions (big news pumps both new and old versions), buy the first new-pair coin created",
      "Two post-migration scenarios: (1) heavily bundled/suppressed — wait for bundle to clear, then test buy with small DCA; (2) organically trending with healthy distribution — buy on the spot after verifying the news",
      "If late: wait for a 60–80% pullback or flash dump, be ready to cut if it doesn't hold",
      "Market is extremely rotational — overstaying is punished, size small enough that full loss is survivable",
      "This phase is the best time to learn: survive choppy conditions now and you'll dominate when volume returns",
    ],
  },
  {
    num: "04",
    title: "How to buy before they explode",
    tips: [
      "Four checks for every coin: narrative (story + attention), community (cult engagement), price action (volume = first signal), legitimacy (on-chain stats + due diligence)",
      "Three profitable coin types: (1) culture coins — viral memes with CT appeal; (2) tech coins — reputable founder, real use case, credible followers; (3) Twitter/influencer coins — extremely popular people + memorable message",
      "Scalping: 5–10% of trenching wallet per trade, check Axiom stats but tolerate more risk since you're in/out fast, zero shame dumping into others",
      "High-momentum runners: legitimacy matters more, tolerate drawdowns if story/community/legitimacy check out, average out in slices as it runs",
      "Biggest psychological killers: FOMO, impatience, revenge trading — always enter with a clear thesis and plan",
      "Don't over-identify as a community member — you're a trader whose job is to be selfish on exits",
    ],
  },
  {
    num: "05",
    title: "Axiom Pro masterclass",
    tips: [
      "Pulse tab: every new Solana token in real time — filter Pump/Pump AMM only, minimum 15k market cap to remove spam",
      "Key on-chain icons: top-10 holder share, dev holding, snipers (stealth dev wallets), insiders (dev-funded wallets), bundles (hidden supply dispersal), paid Dexscreener updates (positive signal), orange Twitter logo (recycled scam account)",
      "Three Pulse columns: New Pairs (where he spends most time), Final Stretch (approaching bonding threshold), Migrated (higher cap, moved to next stage)",
      "Twitter tracker: add accounts like Elon — get live alerts so you connect viral tweets to new tokens in seconds instead of minutes",
      "Wallet tracker: follow any Solana wallet in real time — use for attention awareness, NOT blind copy-trading",
      "Execution: 30%+ slippage, 0.01–0.05 priority fee, MEV protection on — speed matters more than tiny fee optimization",
      "Fee rebates: every trade generates a small SOL rebate that compounds — has saved thousands over time",
      "Trenching rule: cap trading wallet at fixed SOL amount (e.g. 50 SOL), sweep all profits above that to a separate wallet",
    ],
  },
  {
    num: "06",
    title: "$10K/month beginner's guide",
    tips: [
      "70–75% of traders lose in year one, most of the rest lose in the next five years — only 3–5% are consistently profitable",
      "Narrative + community + price action + legitimacy = the full evaluation framework",
      "Meta = leading market narrative with alpha plays (highest cap) and beta plays (co-plays that follow); betas crash harder in pullbacks",
      "Community strength examples: communities that survived numerous corrections because of cult-like engagement",
      "Wait for 50–80% dips before buying — nearly every memecoin experiences multiple major drawdowns",
      "Risk: turned $500 into $104k at 18, then lost most of it from poor risk management — making money is easier than keeping it",
      "Trench with ~50 SOL; whenever you grow above that, move excess to a treasury wallet",
      "Journal four questions after every trade; this 5-minute habit separates short-term wins from long-term consistency",
    ],
  },
  {
    num: "07",
    title: "Shortest trading guide ever",
    tips: [
      "Three coin types: culture (memes, viral animals), technology (reputable devs, real use case), news (current tweets/headlines tied to someone with reach)",
      "Fast research flow: watch Axiom Pulse for volume spikes → click through to Twitter → check mutuals and followers → assess narrative, community, price action in seconds",
      "No technical analysis — memecoins are pure attention markets",
      "Two styles: scalping (fast flips on short-lived hype, never bag-hold) and high-volume runners (strong narratives, average in/out, looking for at least 3x)",
      "Mindset: don't chase, sit out when unsure, treat money as zero once in a coin, trade attention not emotions",
    ],
  },
  {
    num: "08",
    title: "Trading memecoins on EVM chains",
    tips: [
      "EVM (Ethereum, Base, Arbitrum, BNB) shares similar code — learn one, apply to all, but adjust from Solana since EVM plays are slower, less crowded, and more narrative-driven",
      "Tools: Banana Gun (Telegram bot) for execution, MetaMask wallet, Dexy for contract safety checks",
      "Contract safety: check if owner address is dead (0x000…) and if 100% of LP tokens are burned — if both true, technically safer to buy",
      "EVM winners are zero or hero: most go to zero but successful ones hold up longer with stronger narratives and backings vs Solana's short-lived hype",
      "Two EVM-favored narrative types: (1) narratives that fit better on ETH/Base than Solana (e.g. $BET — stock buying Ethereum), (2) coins with unusually strong backing (e.g. Video coin with Paradigm followers)",
      "His $200k trade came from one Twitter follow (Dracula account) — curated follows literally pay for themselves",
    ],
  },
  {
    num: "09",
    title: "How to make f**k you money",
    tips: [
      "Step 1 — Obsession: before his first trade he mentally paper-traded for hours every day for two weeks, tracking coins and imagining entries/exits",
      "Step 2 — Setup: Crypto Twitter as Bloomberg for memecoins, Axiom Pro with 11k min market cap and 40% slippage",
      "Step 3 — Community: trading alone is 20x harder; a good group gives more eyes, faster callouts, collaborative research",
      "Step 4 — Journaling: if you don't journal, you're a gambler with no memory — journal reveals patterns and recurring mistakes",
      "Step 5 — Mindset: turned $500 → $104k in a week, then fell to $20k in two months from emotional mistakes — only trade amounts you can mentally consider already lost",
      "F**k you money = living on your own terms, not just a headline number",
    ],
  },
  {
    num: "10",
    title: "10 lessons to $1M",
    tips: [
      "1. Always have a full plan: thesis, catalysts, scaling-out plan, and clear invalidation before clicking buy",
      "2. Narrative is king: memecoins are stories with a chart attached — evaluate with four questions: who sees it, how they react, attention ceiling, how long it lasts",
      "3. Research everything fast: spend ~30 seconds checking Twitter followers, post history, and ticker on Twitter when something catches your eye",
      "4. Don't chase exact tops or bottoms: insisting on perfection creates hesitation and FOMO — focus on conviction over exact entry",
      "5. If it smells off, it probably is: 99% of weird things are intentional — check dev history, bundle %, and whether the news is even real",
      "6. Don't expect the worst, but be prepared: never let one coin become your whole portfolio without taking profits",
      "7. Not every win is a good win: a random KOL pump you didn't plan for is luck, not skill — label it correctly",
      "8. Don't fall in love with bags: if you wouldn't buy at the current price, you should be selling",
      "9. Obsession is the edge: checked new pairs during Cornell lectures, tracked wallets instead of doing homework",
    ],
  },
  {
    num: "11",
    title: "1-minute alpha filter strategy",
    tips: [
      "Three crypto truths: market context matters, attention gives coins value, and history rhymes so past patterns predict current setups",
      "Step 1 — Market: check Axiom's Migrated column — lots of coins quickly graduating to high caps = risk-on; slow migration = dead zone, preserve capital",
      "Step 2 — Narrative: how big is the audience, how will CT react, what's the ceiling of attention, how many bull catalysts exist to extend the run?",
      "Step 3 — Inefficiency: find coins where current price lags the attention they should get based on similar past plays",
      "Journal every major meta, narrative, and trade so your pattern recognition sharpens over time",
    ],
  },
  {
    num: "12",
    title: "$1K → $100K challenge",
    tips: [
      "Started with $1,000 and hit $100k+ — built on a few big winners, not constant wins",
      "Rules: always take initial principal out once a trade runs, never buy back into the same coin unless narrative materially changes, immediately stable profits into USDC",
      "Case study — Poncho: bought at 35k cap as Bonk's sister during Bonk ecosystem mindshare, took ~$15k profit",
      "Case study — SPY (SharpLink Gaming): real NASDAQ stock adopting ETH treasury, caught at $161k cap, ran to ~$1.6M — used past GME/AMC stock-memecoin examples to judge ceiling",
      "Start small, respect your tiny margin for error, and focus on survival while you build experience",
    ],
  },
  {
    num: "13",
    title: "Millionaire at 18: my story",
    tips: [
      "Started with $500 graduation gift, lost it in 2 days, tried again with $300 Christmas money, lost it in 3 days — third attempt with last $500 became the one",
      "Turned $500 → $54k over summer, then $20k single trade on Cleo pushed to six figures, but round-tripped $104k down to $1.8k from careless trading",
      "Reset: physically wrote thesis for every trade, consulted friends before executing, climbed back to $300k+ then eventually $1M",
      "Left Cornell, moved to Miami with James and Shama to trade full-time",
      "Key lessons: you will round-trip, proper risk management (treat every dollar as already lost), have a system (thesis, catalysts, invalidation, exit strategy), your network is your net worth, obsession guarantees success",
    ],
  },
  {
    num: "14",
    title: "$2.1M strategy & mindset",
    tips: [
      "Memecoins are today's 90s dot-com bubble: most are trash, but a few winners create generational wealth if you understand narratives early",
      "The turning point: raw grind and obsession weren't enough — he needed a repeatable system and risk management after blowing $104k → $1.8k",
      "Alpha filter: (1) assess market conditions and identify current alpha + beta narratives, (2) evaluate narrative with four questions, (3) identify price-narrative inefficiency",
      "Videocoin case study: 30k cap despite strong backers and live app in hot tech narrative — sized in, rode it, took ~$200k from ~0.3 ETH",
      "Every memecoin exists to extract money — devs build narratives to offload bags; accept this and mentally treat money as already gone",
      "Not every win is a good win: if you broke your own criteria and got lucky, that reinforces gambling not skill",
      "Weaponize ADHD: use low attention span to investigate everything, but only act on what passes the filter — one great trade beats a hundred small scalps",
    ],
  },
  {
    num: "15",
    title: "Memecoin millionaire in 23 minutes",
    tips: [
      "Obsession + realistic goals + understanding capital rotation = the formula",
      "Use flow state theory: set profit goals that are challenging but not impossible — too small = boredom, too big = anxiety and bad decisions",
      "Capital rotation: attention and liquidity constantly move between narratives — know which meta is leading NOW",
      "For every coin, write a thesis: who it speaks to, why they'll care, future catalysts, where attention caps out",
      "Deliberate practice: treat every coin — whether or not you buy — as practice; analyze, predict, then review what actually happened",
      "Missing big runners should sting — that pain drives you to dissect mistakes and grow",
    ],
  },
  {
    num: "16",
    title: "$500 → $2M: core lessons",
    tips: [
      "Lesson 1 — You will round-trip 80%: success turns off your risk filter; you keep the pattern recognition even after losing the money",
      "Lesson 2 — Don't confuse a hot market with skill; his early big wins came from Giga May/June environments, not genius",
      "Lesson 3 — Build a system, not vibes: conviction is fake if you can't literally write down why you're taking a trade",
      "Lesson 4 — Pick a lane: specialize in one trading style (scalping vs high-conviction swings) because each requires different temperament",
      "Lesson 5 — You can't do this alone: all serious 7-figure traders are in tight groups sharing research and keeping each other grounded",
      "Networking is the highest-leverage skill in crypto — a single high-quality connection can change your trajectory",
    ],
  },
  {
    num: "17",
    title: "The NEW way to trade on Axiom",
    tips: [
      "Two market modes: hot (coins quickly migrating to higher pools → hunt in new pairs) vs slow (restrict to migrated column only)",
      "99% of new coins are garbage — one rug wipes out many tiny scalp wins; focus on coins that already show real demand",
      "Beginners: live in the Migrated column, not New Pairs",
      "Alpha filter for Axiom: (1) favorable environment, (2) strong narrative (tech/culture/news), (3) asymmetrical upside where price-narrative gap exists",
      "Multi-wallet support: spread buys so you don't appear as a scary top holder, plus structure risk buckets (trenching, spare liquidity, treasury)",
      "Personal rule: trench with fixed SOL (e.g. 100), sweep all profit above that into another wallet",
    ],
  },
  {
    num: "18",
    title: "$1M stolen: security lessons",
    tips: [
      "Scammers drained ~$1M from 100+ hot wallets via a legit-looking partnership call on Microsoft Teams — even official clients can be weaponized",
      "Surface-level checks failed: the scam account had VC backing appearance, big followers, mutuals, and professional branding — all manufactured",
      "Real attack vector: malware injected through the third-party video call client during screen share — no downloads, no suspicious links needed",
      "Red flags found after the hack: follower count was obviously botted, previous handle was tied to a rugged project",
      "New rules: never join third-party calls on any device with wallets unless YOU are the host; keep only actively traded capital in hot wallets, everything else in cold storage or fiat",
      "Check handle history, look for prior rugs, cross-check founders with people you personally trust from real detailed experience",
      "Skills and experience are more durable than money — he intends to make it all back",
    ],
  },
  {
    num: "19",
    title: "Watch this before you trade",
    tips: [
      "Crypto is the next major financial infrastructure shift (like early internet) — but the wild west asymmetric upside phase is temporary",
      "Your edge is NOT finding the next Amazon and holding — it's adapting to narratives and conditions as they change",
      "Strategies that worked in one phase stop working once the market becomes saturated and tools level the playing field",
      "Edge = processing public information faster and with more context than others, not secret insider plays",
      "A good win has a thesis, edge, and reusable mental model — a random FOMO win teaches you nothing and creates dangerous overconfidence",
    ],
  },
  {
    num: "20",
    title: "Master trading psychology in 10 minutes",
    tips: [
      "Core shift: isolated thinking (obsessing over one coin's chart) vs thinking in context (evaluating every trade against market, narrative, and personal context)",
      "Three-part context checklist before every trade: (1) market context — BTC trend, on-chain volume, capital flow, (2) narrative context — where is this coin in the ignition → mania → exhaustion cycle?, (3) personal context — what does this trade mean for your capital and goals?",
      "Solana on-chain volume down ~90% from peak — mindlessly trading new microcaps is currently low-edge",
      "Narrative exhaustion example: Launchcoin went through ignition → parabolic pump → copycats → oversaturation → realization the model doesn't work",
      "This market demands patience: spend more time learning and researching than scalping every new pair",
    ],
  },
  {
    num: "21",
    title: "Full risk management course",
    tips: [
      "Making money is easier than keeping it — most don't blow up from bad picks but from oversized trades, emotional decisions, and lax security",
      "Platform risk: many bots are built by anonymous devs — use YC-backed or auditable platforms (Axiom for Solana, GMGN for BNB, Basebot for EVM)",
      "Capital segregation: hot wallet (daily trading cash), cold wallet (spare capital on hardware), vault (long-term stack that almost never moves), fiat (rent, taxes, emergencies)",
      "Store ALL private keys offline on paper — cloud docs mean a compromised machine = total loss",
      "Position sizing: if losing everything in the market would change your quality of life, you're overexposed",
      "OPSEC rules: dedicated trading device (no calls, no random links), hardware wallet as cheap insurance, ignore airdropped tokens (selling them can trigger drains), never join third-party calls on devices with crypto",
      "The fastest way to make money is to not lose it in the first place",
    ],
  },
  {
    num: "22",
    title: "$10K/day with Nova + Ignite",
    tips: [
      "Uses Nova terminal: Cosmo (all new pairs, 3-column feed) + Ignite (AI algorithm that flags coins matching patterns of previous runners)",
      "Ignite shows: market cap at ping vs current, max multiplier since ping, 1 SOL to ATH metric, plus all on-chain scam indicators",
      "Historical Ignite examples: Fly Pig and Fun caught early before 100x–1000x runs — but Ignite is a filter, not a buy signal",
      "Four-box narrative test: (1) clear story that makes people believe it goes higher? (2) who's behind it? (3) realistic catalysts? (4) who buys 5x higher (your exit liquidity)?",
      "Don't scalp 50 new coins a day — beginners lack intuition and one rug wipes many small wins; start from graduated/migrated coins",
      "Three-pillar alpha filter: environment (Ignite pings and multipliers today), narrative strength (four-box test), asymmetrical upside (early enough that reward >> risk)",
    ],
  },
  {
    num: "23",
    title: "Ultimate 2026 investing guide",
    tips: [
      "Late-stage bull run driven by global liquidity (M2, central bank balance sheets) — Bitcoin is the ocean that lifts or sinks everything",
      "Liquidity wave may crest around mid-late 2026 implying a brutal down-cycle afterward — you're not early, but there's still opportunity while it flows",
      "Sector flow cycle: euphoria → fatigue → cooked → rotation — your edge is reacting fast when a sector enters early euphoria, or predicting rotation with a structured thesis",
      "Narrative analysis: story (differentiated, memorable, culturally aligned), storytellers (doxxed devs, VCs, big accounts), capitalization path (catalysts, defined buyer base)",
      "99% of new coins have no story, no team, no path to new buyers — they exist to grind liquidity; intentionally filter them out",
      "Build a narrative almanac of what has worked historically and why — run a structured thesis for every coin or skip",
      "Golden rule: every position and every dollar in crypto is already zero — if losing it would change your real-life quality, you're oversized",
    ],
  },
  {
    num: "24",
    title: "$3M at 20: discipline is the edge",
    tips: [
      "Trading success is mostly mindset, not strategy — discipline = doing what you said you'd do, especially when you don't feel like it",
      "His edge: fast reaction + narrative reading — waits for markets to turn euphoric, then sizes into the few trades that match his style; can sit out for weeks",
      "Stay in your lane: if a setup doesn't fit your thesis and style, it's not your trade even if others are making money on it",
      "Before every entry: define why you're buying, what catalyst you expect, how you'll take profits — decisions under pressure just follow the plan",
      "Life discipline = trading discipline: pick two small daily non-negotiable habits (gym, clean eating) — consistently doing them builds identity as a disciplined person",
      "Greed isn't bad, but uncontrolled greed is: if a P&L is enough to improve your life, taking profit is justified even if it's not the perfect exit",
      "When you mess up: fully own it, feel the pain, write out what went wrong and how you'll adjust",
    ],
  },
  {
    num: "25",
    title: "The boring strategy that works",
    tips: [
      "Sector reaction strategy: instead of farming every new coin, wait for specific sectors to enter euphoria, then selectively bet on the best narratives",
      "Four indicators of sector euphoria: (1) even mediocre launches in the narrative get traction, (2) sector leaders' charts show parabolic runs, (3) strong rising on-chain volume, (4) explosive bullish chatter on Twitter",
      "React, don't predict: you don't guess the next hot sector — you react once liquidity clearly rotates in and euphoria begins",
      "Case studies: AI coins late 2024 (GOAT etc. → billions), ICM via Launchcoin (missed 300M move but still made six figures farming launchpad coins), BNB memes (any coin with CZ narrative pumped)",
      "Narrative analysis inside euphoria: story (new, viral, tied to sector core), storyteller (founder track record, community strength), timing (concrete catalysts and exit windows)",
      "Most money comes from a few short euphoria periods — you may sit on your hands for weeks, then go all-in on focus when the sector flips to easy-mode",
      "Offers a worksheet to systematize: sector/phase, coin cap, comparables, leader performance, targets, invalidation, rotation signals",
    ],
  },
  {
    num: "26",
    title: "Lost $100K, here's what fixed it",
    tips: [
      "Ran $500 → $104k as a teenager, then round-tripped to $1.8k — a lot of that six-figure win was favorable market conditions, not skill",
      "Rock bottom: partying, gaming, mentally checked out — but confronting why do I even care about trading became the most important moment",
      "His why: not wanting life defined by a game rank, not wanting to live in his parents' basement, wanting to make their sacrifices mean something",
      "Comeback: accumulated JoeCoin at $5M cap (even averaged down to $3.8M), set concrete milestones ($100k, $300k, $750k, $1M)",
      "If your only why is money, it has no substance — numbers alone won't carry you through the darkest periods or let you enjoy winning",
      "Exercise: imagine you're wiped out instantly — your first emotional reaction is your real why; bring it to mind on every trade",
      "He who has a why to live can bear almost any how",
    ],
  },
  {
    num: "27",
    title: "2026 beginner's free course",
    tips: [
      "Almost all memecoins go to zero — the only goal is to extract profit before they die; there is no magic indicator",
      "Step 1 — Narrative: only act when a coin's story clearly fits a strong trend with some originality; examples: commodities meta (olive oil coin), influencer leverage, TikTok meta (Penguin coin)",
      "Step 2 — Entry: assume every new coin has a 20–50% hidden bundle; wait for the bundle to exit, then consider if the coin shows signs of life with fresh volume",
      "Be greedy with your entry — wait for max pessimism or post-bundle conditions where you're comfortable with the downside",
      "Step 3 — Sizing: use sizes small enough that a total loss barely affects your emotional state; $500 into a meme coin turned into ~$20k because narrative and entry were good",
      "His win rate can be negative, but tight entries and sizing mean big winners more than offset frequent small losses",
      "He often logs on with the mindset I do not want to trade — only acting when a coin's narrative truly stands out",
    ],
  },
];
