import type { MemecoinMindsetLesson } from "./memecoinMindsetLessons";

export const SOL_MAFIA_PLAYBOOK_LESSONS: MemecoinMindsetLesson[] = [
  {
    num: "01",
    title: "Ultimate memecoin vocabulary",
    tips: [
      "Market cap matters more than price per token — use it to frame entries and targets (small caps 10k–100k move fastest)",
      "Rugpull = dev pumps then sells; most tokens are effectively rugs over time, so the edge is timing your trade before the rug",
      "Bundling = dev uses many fake wallets to simulate real buyers and inflate apparent demand — heavily bundled coins are extremely dangerous",
      "MEV bots front-run you by scanning the mempool and outbidding your tip — enable MEV protection and pay appropriate fees",
      "Snipers are among the first ~20 wallets with extremely low entries — they have massive influence when they sell",
      "Paying the DEX (Dexscreener update) is when a project pays to update its profile — often gives a short-term price spike",
    ],
  },
  {
    num: "02",
    title: "Phantom wallet setup",
    tips: [
      "Install Phantom browser extension, create wallet, write down the 12-word seed phrase on paper and store it physically (never digital)",
      "Buy SOL directly via card through Coinbase Pay/MoonPay/Stripe, or receive from a CEX like Coinbase",
      "Your public address is like your house address (shareable) — your seed phrase / private key is the key to your house (never share)",
      "Create multiple wallets inside Phantom for different purposes (bots, strategies, treasury)",
      "To connect to trading bots like BullX, you paste your private key — treat this with extreme care",
    ],
  },
  {
    num: "03",
    title: "How much money to start",
    tips: [
      "Start with ~$500 and mentally treat it as tuition you're prepared to lose while you learn",
      "Don't place orders under ~$50 (0.3 SOL) because fees (~$5–15 per trade) eat too much of smaller positions",
      "Assume there's essentially a 100% chance you lose your initial investment over the first weeks — your early losses buy experience",
      "All the big traders he knows lost a few hundred first before turning small amounts into much larger profits once they had experience",
    ],
  },
  {
    num: "04",
    title: "Trade before they explode",
    tips: [
      "Buying at 9k market cap: downside ~33% if it drops to start, upside 160%+ (more than double) — buying at 22k: only 42% upside while risking 86% loss",
      "Take initial profits at 100% gain, withdraw principal, let the rest ride risk-free",
      "Short-term metas: event-driven and viral (e.g. Luigi Mangione spawning derivative coins) — blow up fast, fade within weeks",
      "Long-term metas: fundamental value with lasting power (e.g. AI agent trend running for months)",
      "Token filters: volume ≥ market cap, top 10 holders under 15–20%, dev holdings 0% for memes (buy after dev sells), insiders under 10–20%",
      "Start with tiny trades (0.1–0.3 SOL from a 2 SOL bankroll) to learn how graphs move and what natural vs botted price action looks like",
    ],
  },
  {
    num: "05",
    title: "Stop copytrading — track instead",
    tips: [
      "If you copy buys late in the chain (dev → KOLs → regular traders → whales), you're exit liquidity",
      "Instead: use BullX's Top Traders to find wallets with 250k+ realized profits, star and rename them, attach alerts",
      "Treat alerts as confluence, not buy signals — do your own research when tracked wallets enter the same coin simultaneously",
      "Periodically check last-trade dates and remove dead/inactive wallets from your list",
      "Secret trick: check who famous traders follow on Twitter → find low-follower accounts flexing big profits → look up those trades in BullX → match to wallets and tag them",
    ],
  },
  {
    num: "06",
    title: "Insider research strategy",
    tips: [
      "Crypto is one of the only markets where tracking insider wallets via public on-chain data is both possible and legal",
      "Off-chain: drill into big CT accounts' followings → find small friends-and-family accounts with only a few hundred followers who quietly post big P&Ls",
      "If a low-follower project is followed by someone you know is sharp, that's a strong signal to dig deeper and take a small position",
      "On-chain: use Solscan to map wallet networks — where big inflows come from, where funds go, connected wallets",
      "Watch for coordinated early buying across labeled insiders and FNF groups — if a bunch buy a new coin simultaneously, there's likely a private reason",
      "There is no shortcut — the secret is putting in hours of manual research on Twitter and chain, labeling wallets, and understanding behaviors",
    ],
  },
  {
    num: "07",
    title: "Best days and times to trade",
    tips: [
      "Uses Dune Analytics dashboards (Pump.fun, BullX, Photon) to see daily/weekly/hourly volume and token launch data",
      "Memecoins usually slower on weekends, more active Monday–Thursday, roughly 9 AM – 9 PM Eastern",
      "Unexpected news (celebrity events, political shocks) can send coins parabolic at any time — always keep scanning",
      "Some traders prefer quiet hours (fewer launches, easier to review each coin), others thrive in high-volume chaos",
      "Uses Dexa.ai to track narratives and CT mindshare — which themes are gaining attention that might turn into longer-term metas",
    ],
  },
  {
    num: "08",
    title: "5 most common trading mistakes",
    tips: [
      "1. Not taking out initials: de-risk early by pulling original capital at 2x, then scale out in 10–25% chunks as it pumps",
      "2. Full-porting into one coin: good traders risk 10–20% or small fixed amounts per play — treat it like venture capital with many bets",
      "3. Buying bundled/manipulated coins: use tools like Photon Vision and bundle-check bots to spot when 70–80% of liquidity is fake",
      "4. Trading alone: join active discords and voice chats — thousands of coins launching while you only have your own eyes",
      "5. Forgetting fundamentals: don't obsess over 1-minute charts and forget the big picture — meta, narrative, and conviction are what matter",
    ],
  },
  {
    num: "09",
    title: "Mental game before you trade",
    tips: [
      "Set a realistic daily profit target in SOL (like 1–2 SOL), stop trading the moment you hit it — overtrading when up is how you give it back",
      "For every coin you buy, have a written thesis: why you're buying, what it can reasonably reach, what invalidates the idea",
      "Define TP/SL rules in advance and follow them mechanically — sell 50% at +100% to be completely de-risked",
      "Stop-loss thresholds depend on play type: maybe -20% on a weak AI narrative vs -50% max on a high-conviction meme",
      "When up big or down badly, treat it as real money — pull profits into USD when you win, step away and reset when you lose",
    ],
  },
  {
    num: "10",
    title: "The $1M/week scalper (Cupsey)",
    tips: [
      "Cupsey makes ~$1.2M in 7 days using only 0.2–0.5% of his ~$500k wallet per trade (~$1k–3k per position)",
      "Takes ~300 trades per day, constantly sniping new pairs, entering and exiting very quickly",
      "On big runners: scales out in ~25% chunks multiple times as buyers come in — never all in and 2x then exit",
      "On stalled coins: exits entire position quickly, accepts small losses, immediately moves to next coin",
      "The edge is skill, speed, and pattern recognition around narratives, dev behavior, and on-chain signals — not a secret indicator",
      "Fees and slippage mean this style only works once you can trade at least ~$100 per position",
    ],
  },
  {
    num: "11",
    title: "CT tracker: don't trade without it",
    tips: [
      "A CT tracker is Discord-based software monitoring selected Twitter accounts in real time — surfaces events normal X wouldn't highlight",
      "Meme markets are driven by news/narratives — a 5–10 second delay from normal X can be the difference between sniping early or chasing a top",
      "Live test: his tracker sees his own tweet several seconds before it appears on his X client — enough time to decide and execute",
      "He runs one monitor for big crypto news (Elon, Truth Terminal) and a second tracking ~150 low-key insiders",
      "CT tracker builds thesis/conviction (news side), wallet tracker confirms the trade (on-chain side) — use both together",
    ],
  },
  {
    num: "12",
    title: "2025 trading stack",
    tips: [
      "Full stack: Telegram + Phantom + Nova + BullX Neo — Nova for speed-critical sniping, BullX Neo for dashboard and research",
      "Nova's three streams: New Creations (fresh launches), About to Graduate (approaching migration), Graduated (higher cap)",
      "Primary bet is on volume and volatility, not value — watch 5-min and 1-hour volume; strong and rising = stay in, falling = exit",
      "Nova Click Chrome extension adds instant buy buttons directly on token pages for fast snipes",
      "Import Phantom wallet into Nova/BullX by pasting private key — trades execute via Telegram bot",
      "His style: rapid in, out, in, out scalps, deciding quickly whether a coin is getting attention and volume",
    ],
  },
  {
    num: "13",
    title: "$10K narrative strategy",
    tips: [
      "A memecoin goes up because of attention on its narrative — you're betting more people will look at it after you buy",
      "Long-term metas: persistent themes (AI coins, Trump coins) that shift the market for weeks/months",
      "Short-term metas: fast news-driven trends lasting a few days (e.g. Luigi case, livestream rug meta)",
      "To identify the current meta: watch which coins push over 100k+ on your dashboard and look for patterns — many coins riffing on the same idea = meta forming",
      "Wallet tracking as meta detection: see what consistently profitable traders are buying and infer emerging narratives from their behavior",
    ],
  },
  {
    num: "14",
    title: "MEV protection & fee settings",
    tips: [
      "MEV bots scan the public mempool, front-run you by outbidding your tip, push price up, then dump — MEV protection routes through private validators",
      "When to use MEV protection ON: regular buys over ~1 SOL where you'd get farmed for slippage",
      "When to turn MEV OFF: sells (bots rarely target), small buys (under 0.2–0.3 SOL), sniping new pairs/migrations (speed > protection), extreme volatile laser plays",
      "Nova settings: buy tip and fee configurable; MEV Protect Buy = ON with Auto route for normal trades, OFF with Ultra route for sniping",
      "BullX Neo: define separate order presets with different priority fee, slippage, and MEV toggle — pick preset based on the trade",
    ],
  },
  {
    num: "15",
    title: "Full 2025 course: Axiom + Rapid",
    tips: [
      "Turned heavy student-loan debt into six figures in six months — positions this as an A–Z beginner workflow",
      "Import prebuilt new pairs / final stretch / migrated filters from his Discord into Axiom to cut out most rugs",
      "Wallet tracking = the single most important edge for beginners; import curated profitable wallet lists and watch when top traders enter/exit",
      "Rapid Launch on one monitor showing Twitter, Axiom on the other showing new/migrated pairs — when key accounts tweet, instantly look for the associated token",
      "Research flow: check Twitter account, website, who created it, whether the CA is on the official site, which known accounts are engaging",
      "Success comes from repetition: staring at Pulse, Rapid, and Discord every day watching how good wallets and narratives behave around launches",
    ],
  },
  {
    num: "16",
    title: "$71K week strategy",
    tips: [
      "Only trades memecoins with a clear, compelling narrative — aims to buy very early on Axiom new pairs, then sell quickly for asymmetric R:R",
      "A narrative is a 1–2 sentence story explaining what the coin is and why it's going up — use it to estimate realistic market cap ceiling",
      "A KOL (known operator) is a big profitable trader — when they buy, attention and volume spike because people wallet-track and copy them",
      "Clean branding wins: sharp images, short memorable tickers beat blurry or low-effort variants when multiple coins compete on the same narrative",
      "Vamping: a new better version of a narrative steals volume from existing coin — recognize which one the crowd will converge on",
      "Buying at 9k cap and cutting if it rugs costs ~15%, but upside to 20k–100k+ is 2–10x — buying later at 40k has worse R:R for the same absolute move",
    ],
  },
  {
    num: "17",
    title: "$100K/month interview",
    tips: [
      "Background: started making money at 13 reselling sneakers with bots, dropped out of Fordham with $70k debt, discovered memecoins via straight to a prison coin (lost 3x)",
      "Started with 2–3 SOL, built portfolio through YouTube tutorials and referral commissions, now over $600k",
      "Focuses on new pairs, streams 8–16 hours daily on Twitch, believes Solana trenches still offer $10k daily opportunities",
      "Misses the tweet play era with low dev allocations (3–5%) that instantly pumped on narrative catalysts",
      "Mount Rushmore of traders: West, Cupsey, DV, and Cented — honorable mentions to longer-term holders like Querty, Rowdy, and Xander",
    ],
  },
  {
    num: "18",
    title: "The $700K Axiom setup",
    tips: [
      "Every trade pays ~2.25% per side (~4% round-trip) in Axiom + Pump.fun fees — scalps under that threshold are not profitable",
      "Three presets by position size: under 0.25 SOL (low fees, 60% slippage), 0.25–0.75 SOL (moderate fees, 100% slippage), over 1 SOL (quick-buy aggressive + normal conservative)",
      "Quick buy over 1 SOL: ~0.03 bribe, 0.02 priority, 300% slippage, MEV OFF — pure speed race on fresh coins",
      "Normal buy over 1 SOL: ~0.01 bribe, 0.002 priority, 100% slippage, MEV reduced",
      "MEV off on quick buys because fresh coins haven't attracted MEV bots yet — protection adds latency with minimal benefit",
      "Axiom filters: new pairs require $100 min volume; final stretch requires 10k min cap and 0.5 SOL global fees; migrated requires 10k cap and 2 SOL global fees",
    ],
  },
  {
    num: "19",
    title: "5 things I wish I knew",
    tips: [
      "1. Real vs fake charts: real coins have natural spawning with buys and sells; fakes have one huge first candle straight to high cap with fresh wallets and no sells",
      "2. Holder distribution (DEX): no single non-locked wallet should control more than ~5% at higher caps; use bubble maps to detect multi-walleting",
      "3. Don't trade alone: join discords, watch Twitch streamers — use streams to learn how experienced traders think, not to mindlessly copy",
      "4. Wallet tracking is the most important part: overlay tracked wallets on charts to predict how coins move based on specific players' behavior",
      "5. Paper trade first: mark hypothetical entries on charts, track outcomes in a document, build pattern recognition without losing real money",
    ],
  },
  {
    num: "20",
    title: "$4,930 day recap",
    tips: [
      "10 hours of trading, ~17-second average hold time, ~55% win rate — scalping new Solana memecoins across multiple wallets",
      "Winning pattern: spot narrative on Twitter/news → snipe first or cleanest ticker at 8–10k cap → sell into early strength as volume stalls",
      "Sell into green candles when order flow shows resistance — recognize when devs or bundles are applying heavy sell pressure",
      "Biggest fumble: bought Sydney Sweeney trend coin early, sold for tiny $100 loss out of fear, then it exploded when Elon interacted with the trend",
      "Lesson: during strong obvious trends where everyone is posting, holding at 20k-type levels can be safer because secondary attention can send it much higher",
    ],
  },
  {
    num: "21",
    title: "$4,040 in a dead market",
    tips: [
      "Most coins topped at 10–15k cap with devs and bundlers immediately selling into any buying pressure — forced 30-second scalps",
      "Best-performing plays were Twitter tracker plays — coins based on trending tweets from influential crypto figures",
      "Biggest loss: blindly bought a call from voice chat without doing research — coin was full-stacked by dev and other traders (-$600)",
      "Lesson: stick to Twitter tracker plays and news-based narratives, avoid gambling on random coins, never blindly buy calls without research",
    ],
  },
  {
    num: "22",
    title: "$4,180 day (rage quit)",
    tips: [
      "Series of vamp situations: identical tickers relaunched and he ended up on the wrong version multiple times",
      "Rage quit despite being up $4.1k because his vamp attempt got no buyers while another redeploy with same branding ran to 40k",
      "Goal is always to be top holder on the leaderboard for each token — means you extracted maximum value from the move",
      "Lesson: emotional swings (YouTube issues, fear after losses, rage quitting) make you leave huge upside on the table even on green days",
    ],
  },
  {
    num: "23",
    title: "Starting from $0",
    tips: [
      "Step 1 — Get $500–1k capital through referral commissions, content clipping bounties, or a regular job",
      "Step 2 — Study before trading: watch live traders on Twitch, track their wallets, mentally map how high could this go without being in the trade",
      "Step 3 — Paper trade: mark hypothetical entries on charts, track outcomes in a document, build timing and exit skills",
      "Step 4 — First real trades: start with $500 portfolio and 0.25 SOL per trade, only high-conviction narrative plays",
      "Step 5 — Risk management: trade like you're still broke even as the account grows, sell 50% at 2x, use Axiom auto-sells where possible",
      "Core mindset: you cannot trade like you're rich if you still think like you're broke — be decisive but cautious from a disciplined system, not desperation",
    ],
  },
  {
    num: "24",
    title: "$6,030 day: hold your conviction",
    tips: [
      "Biggest win was a PolyMarket trading terminal coin — sold too early after a shakeout and missed generational upside as it ran from tens of thousands to hundreds of thousands",
      "Main lesson: when you know the tech/narrative is good, trust your read and hold through noisy price action — once one big player posts it in a group, it can rip extremely hard",
      "Market is still mid and hard to push above ~20k cap, but grinding 24/7 with a small side wallet can be cracked given all the opportunities",
      "Patience and minimizing large losses matter more than catching every move",
    ],
  },
  {
    num: "25",
    title: "-$626 day: lessons from Mayhem",
    tips: [
      "Lost ~$600 following calls from alpha group friends who immediately dumped on him — don't trust clout or on-chain friends blindly",
      "Pump.fun Mayhem mode bot can pull liquidity and sell more than total supply — extracted ~$500k from retail in a day by trapping people",
      "Round-tripping (small P&L swings around breakeven) = your entries are too obvious and your size/visibility is being actively farmed",
      "New features from platforms can be pure extraction mechanisms — test and observe before sizing up",
      "A -$600 day is acceptable relative to a +$6k prior day — stay aligned with broader conditions and keep losses small",
    ],
  },
  {
    num: "26",
    title: "$11,200 day: narratives + fee farming",
    tips: [
      "About half the $11.2k came from directional trading, the other half from fees captured by a dev-linked wallet that farms bonding and trading fees",
      "Grokcoin: viral YouTube joke with Coffeezilla collab — rode from low cap through bonding, experimented with smaller initial size to encourage others to buy over him",
      "Bubba (Bill Clinton meme): got in at 5k from Epstein emails going viral, scaled out through migration for ~$2k profit",
      "In the current environment you need to get dirty, identify strong timely narratives, deploy them well on the first attempt, and avoid forcing setups when vibes are bad",
    ],
  },
  {
    num: "27",
    title: "$2,150 in two hours",
    tips: [
      "Best trade: Paul coin built around viral paw template with 1.6M views — got in at 5k cap, scaled out for ~$1.8k profit",
      "Pattern: enters on reflex from narrative + influencer flow, then decides whether the underlying narrative justifies holding",
      "Recurring mistake: trading like he's poor — taking tiny wins after big drawdowns even though capital should allow more risk on strong narratives",
      "Win rate ~70% but average hold time only 16 seconds — too short, reflects fear-based scalping instead of conviction holds",
      "Lesson: holds through the dump then sells on the first bounce, when that bounce often means new buyers understand the narrative and he should stay in",
    ],
  },
];
