import type { MemecoinMindsetLesson } from "./memecoinMindsetLessons";

export const STRATEGY_PLAYBOOK_LESSONS: MemecoinMindsetLesson[] = [
  {
    num: "01",
    title: "Pocket change to generational wealth",
    tips: [
      "Started with 10 SOL (~$1k) after getting his wallet drained of $20k — grew it to $30k+ profit in under a week",
      "Monday alone: 10 SOL → 63 SOL by scalping + catching a tap-to-earn narrative coin (6 SOL in, 24 SOL out)",
      "Main edge is getting in extremely early at 6k–30k market cap before coins run to six figures, then selling into euphoria",
      "Leans heavily on Twitter for narratives — viral posts, political memes, Elon tweets — then apes fast as one of the first buyers",
      "Uses a Twitter tracker, Axiom trading platform, and wallet tracker while spending 8–10 hours a day at the screen",
      "Core lesson: \"They took my money, not my skill\" — capital is replaceable, skill and composure are the real assets",
    ],
  },
  {
    num: "02",
    title: "The $2,000/day full strategy",
    tips: [
      "Focus on the EU session (2 AM – 10 AM EST) — less PvP, fewer competing launches, slower price action makes it easier to identify winners",
      "Trade almost exclusively new pairs that just launched at 5k–8k market cap — best risk-to-reward because losers cost 10–25% while winners can 10x+",
      "Size each trade at 2–5% of your portfolio (e.g. 0.4–1 SOL on a 20 SOL account)",
      "Cut losers fast at 20–50% down max — take initial investment out at 2x so the position becomes risk-free, then let runners ride",
      "Scan new pairs for two signals: strong volume AND a fresh narrative — if it's recycled or has no real traction, skip it",
      "Fresh narratives that win: familiar IP with a unique spin (e.g. Japanese Pepe, a Dexscreener Easter egg coin) — familiarity + novelty = biggest runners",
      "Set personal rules: max per-trade risk, max daily loss, max loss per hour, and limited buybacks — anything outside these rules is gambling",
    ],
  },
  {
    num: "03",
    title: "The 100x blueprint",
    tips: [
      "Spotting big memecoin winners uses a four-part framework: Virality, Memeability, Narrative, and Resemblance",
      "Virality: are people already talking about this coin or topic across social media and chats?",
      "Memeability: is the coin funny and understandable to people outside crypto? Can normies get it?",
      "Narrative: what's the real-world story or hook? Mainstream attention (like Peanut the squirrel's news story) drives the hardest runs",
      "Resemblance: does the coin remind people of a bigger existing brand or asset? (e.g. XBT evokes Bitcoin)",
      "Practical move: search the ticker and related terms to check for existing chatter before buying — if no one is talking about it yet, the narrative hasn't caught",
    ],
  },
  {
    num: "04",
    title: "Memecoin filters that print",
    tips: [
      "Treat filters like a fishing net — tighten or loosen them depending on market conditions, session volume, and the type of play",
      "New pairs: 60–70% of the time use no metrics filters, just filter by launchpad (Pump.fun, Bonk, Believe) — during high-volume sessions add a 7k minimum volume/market cap filter",
      "Twitter tracker + keyword filters: when a narrative tweet drops (e.g. Elon tweets about dogs), instantly add keyword filters so only matching coins show up and you can snipe the first relevant ticker",
      "Final stretch filters: set bonding curve to ~30%, age to 4–5 min in high volume (up to 10 min in low volume), and periodically expand to 60 min to catch slow cookers that picked up volume late",
      "Anti-rug safety: set max sniper % to ~5% and max dev holding to ~7–8% so coins where insiders or devs control too much supply never even appear",
      "Migrated tab: set a minimum market cap (~40k) to only see projects that actually have traction — this also reveals what current metas the market is rewarding",
    ],
  },
  {
    num: "05",
    title: "Getting rich with crypto in 2025",
    tips: [
      "Yes it's still possible, but the game has changed — the edge shifted from blind dexscreener aping to exploiting Solana/BONK meta, Twitter flow, and tight execution",
      "Launchpad warfare between Pump.fun and Bonk changed which narratives and KOLs matter — BONK ecosystem is heavily Asia-driven (Chinese, Japanese, Korean communities)",
      "Run a real-time CT/Twitter tracker alongside your trading terminal so you can react instantly when high-motion KOLs post",
      "Recognize viral phrases and in-jokes early — e.g. the Michael Saylor \"it's going up forever, Laura\" meme was a 30k → runner play",
      "Trading solo is extremely hard — trade in group chats where people constantly scan new launches and share early calls (not signals groups, but active scanning teams)",
      "Adapt to the current meta: track narratives and KOLs systematically, treat it like a craft, and put sustained daily hours into the trenches",
    ],
  },
  {
    num: "06",
    title: "Axiom settings masterclass",
    tips: [
      "Three fee presets: Normal (moderate priority for standard EU session trades), Sniper (0.1–0.15 SOL high fees + 1000% slippage for contested CT plays), and Low (near-zero fees for offloading dead tokens and test buys)",
      "Fast-switch between presets so you can flip from normal to sniper mode in seconds when a tweet play appears — never leave sniper fees on during normal buys",
      "Import curated wallet lists and use Axiom's wallet tracker to monitor whales, insiders, bundlers, and strong devs — bell notifications only for the highest-signal wallets",
      "Wallet groups let you cluster bundlers/insiders so you can recognize collective behavior and avoid becoming their exit liquidity",
      "Pulse tracker overlays live new/migrated pairs on your chart so you can monitor PvP opportunities without juggling tabs",
      "Bubble maps: gray bubbles = safe mid-sized holders, highlighted clusters = multi-wallets or bundles — if one entity controls 20%+ of supply, it's likely a dump setup",
      "Wallet funding panel: if multiple top holders were funded from the same exchange at nearly identical times, that's a strong bundle/rug indicator — avoid regardless of how the chart looks",
      "Search bar OG detection: always sort by 1h volume and check OG (oldest contract) before aping — he lost 65 SOL buying the wrong ticker variant by skipping this step",
      "Set auto-snipe amount (0.5 SOL/fixed) instead of variable sizing on competitive plays",
      "Set your region correctly (US East/West/Central) instead of global — wrong region = extra latency = missed fills on competitive plays",
    ],
  },
  {
    num: "07",
    title: "The only 2 strategies you need",
    tips: [
      "Strategy 1 — Attention filter (new pairs): sit on the new pairs section with no filters during EU session, watch every launch, and spot unique clickbait narratives that pop visually",
      "Wait a few seconds to see if volume and market cap start ticking up — only click in if it's getting real traction, not recycled or faked",
      "Entry options: quick buy when early traction shows, OR open the chart and buy the first small dev sell/dip for a better entry",
      "Strategy 2 — Break of the low (final stretch): for coins about to graduate off the bonding curve — set bonding curve to 90%, age 8–15 min, min market cap ~$10k, min global fee 0.3–0.5",
      "Evaluate: good wallets in the coin + fresh narrative + strong community/dev with active X posting and CT presence",
      "Find a key swing low on the chart, wait for price to break it during an EU session retrace, then buy the break or the reclaim bounce above it — creates a double-bottom structure",
      "Only trade EU session 2 AM – 10 AM EST — when the session ends, stop trading even if you might miss plays later",
      "Journal every single day: what you did right/wrong, how you felt, what to improve — treat trading as a business, not a jackpot",
    ],
  },
  {
    num: "08",
    title: "3 books that built a millionaire",
    tips: [
      "Trading in the Zone (Mark Douglas): the foundation for thinking in probabilities instead of emotions — treat each trade as one data point in a large sample, not a life-or-death event",
      "Best Loser Wins (Tom Hougaard): reframe losses as normal operating cost — stop revenge trading and accept red days as part of the process",
      "The Alchemist (Paulo Coelho): reinforces purpose, patience, and trusting the journey rather than obsessing over the end result",
      "Core takeaway: traders fail from emotional mistakes (panic, overleveraging, breaking rules), not from lacking strategy — success comes from psychology, discipline, and detachment from individual outcomes",
    ],
  },
  {
    num: "09",
    title: "Trading in a slow market",
    tips: [
      "Traders lose in slow markets because they keep using high-volume strategies (sniping everything, chasing hype) that no longer fit the environment",
      "With fewer active narratives, strong coins actually stand out more clearly — disciplined traders can lock into the one or two real runners and ride them longer",
      "Tighten your narrative filters: only trade coins with genuinely fresh, unique narratives — recycled themes die faster in low volume",
      "Hold fewer positions but with higher conviction — shift from rapid-fire scalping to patient, selective entries on the best setups",
    ],
  },
  {
    num: "10",
    title: "Unf*ck your trading mindset",
    tips: [
      "Shift from \"How do I make the most money today?\" to \"How do I be the best, most disciplined trader today?\" — focus on following rules, not outcomes",
      "Never trade with money you can't afford to lose — if it's bill money or survival money, you physically cannot be unemotional",
      "Treat risk capital as already gone before you enter — define risk per trade, accept that losses are normal even for the best traders",
      "Fear of losing is often ego: you told people you're a trader, so admitting a loss hurts your identity more than your wallet — drop the ego",
      "Discipline in life = discipline on charts: if you can't wake up on time, clean your room, or hit the gym, that same sloppiness bleeds into impulsive trading",
      "He spent 2 years making no real money, then did a 3-month monk mode (extreme discipline in all life areas) which finally transformed his trading psychology",
      "The goal: follow your rules so consistently it becomes second nature, until you reach a flow state where emotions and ego are out of the way and you move with the market",
    ],
  },
];
